### ISSUE TITLE
`pip install wad` does not put any executable on path

### ISSUE THREAD

**Issue by OndraZizka** [CERN-CERT/WAD#19]
I've installed WAD using `pip install wad`.
Now I am looking for any executable, but there's nothing to run. `wad` is not on classpath, and `pip show wad` shows me a dir with some scripts but no executable or help how to run it.

I suggest to either document where the wad script is or fix the installation.

**Comment by nikofil** [comment]
wad's latest version should also now provide a binary - closing.
