### ISSUE TITLE
'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte

### ISSUE THREAD

**Issue by TheManFromEarth1** [CERN-CERT/WAD#30]
Happened with:
https://web.de/
https://www.spin.de/

**Comment by nikofil** [comment]
Should be fixed now (v0.4.5).

**Comment by johnanortega** [comment]
I have the same problem with granada.org

**Comment by johnanortega** [comment]
Hello, other fix can be this.
In wad -> detection.py -> line 53:

content = content.decode(encoding='UTF-8',errors='ignore')

**Comment by nikofil** [comment]
It works for me for granada.org - how are you executing it?

**Comment by johnanortega** [comment]
It's true, it works fine. My virtualenv had not updated to 0.4.5.
Excuse me
